"""create resume analyses table

Revision ID: 778b5994bcd0
Revises: 6d500b58674d
Create Date: 2026-09-28 16:40:48.847439

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '778b5994bcd0'
down_revision: Union[str, Sequence[str], None] = '6d500b58674d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('resume_analyses',
    sa.Column('resume_id', sa.UUID(), nullable=False),
    sa.Column('overall_feedback', sa.Text(), nullable=False),
    sa.Column('strengths', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.Column('missing_skills', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.Column('recommended_skills', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.Column('project_feedback', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.Column('improvement_suggestions', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['resume_id'], ['resumes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('resume_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('resume_analyses')
    # ### end Alembic commands ###
