"""add certifications to resumes

Revision ID: add6998fcb1e
Revises: 778b5994bcd0
Create Date: 2026-09-29 12:33:07.542080

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'add6998fcb1e'
down_revision: Union[str, Sequence[str], None] = '778b5994bcd0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('resumes', sa.Column('certifications', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('resumes', 'certifications')
    # ### end Alembic commands ###
