"""add experience range to jobs

Revision ID: ca683151b1ff
Revises: 5cc51e8dff2a
Create Date: 2026-10-02 18:14:33.306178

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ca683151b1ff'
down_revision: Union[str, Sequence[str], None] = '5cc51e8dff2a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('min_experience_years', sa.Float(), nullable=True))
    op.add_column('jobs', sa.Column('max_experience_years', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jobs', 'max_experience_years')
    op.drop_column('jobs', 'min_experience_years')
    # ### end Alembic commands ###
