"""create ats analyses table

Revision ID: f8fd15c00d81
Revises: 7327c0630ce4
Create Date: 2026-09-29 20:26:23.993820

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f8fd15c00d81'
down_revision: Union[str, Sequence[str], None] = '7327c0630ce4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ats_analyses',
    sa.Column('resume_id', sa.UUID(), nullable=False),
    sa.Column('overall_score', sa.Integer(), nullable=False),
    sa.Column('completeness_score', sa.Integer(), nullable=False),
    sa.Column('skills_score', sa.Integer(), nullable=False),
    sa.Column('experience_score', sa.Integer(), nullable=False),
    sa.Column('projects_score', sa.Integer(), nullable=False),
    sa.Column('education_score', sa.Integer(), nullable=False),
    sa.Column('certifications_score', sa.Integer(), nullable=False),
    sa.Column('structure_score', sa.Integer(), nullable=False),
    sa.Column('contact_score', sa.Integer(), nullable=False),
    sa.Column('strengths', sa.JSON(), nullable=False),
    sa.Column('improvements', sa.JSON(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['resume_id'], ['resumes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('resume_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ats_analyses')
    # ### end Alembic commands ###
